# Generated by Django 5.1.3 on 2024-12-04 20:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('UserGuide', models.TextField()),
                ('Description', models.CharField(max_length=100)),
                ('SerialNumber', models.PositiveBigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FUll_Name', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=254)),
                ('Subject', models.CharField(max_length=100)),
                ('Message', models.TextField()),
                ('CreatedDate', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Feedbacks',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('LocationId', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('Country', models.CharField(blank=True, default='Rwanda', max_length=100)),
                ('Provence', models.CharField(max_length=100)),
                ('District', models.CharField(max_length=100)),
                ('Village', models.CharField(max_length=100)),
                ('Streetcode', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Locations',
            },
        ),
        migrations.CreateModel(
            name='Medical_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('HID', models.PositiveBigIntegerField()),
                ('BID', models.PositiveBigIntegerField()),
                ('DOB', models.DateField()),
                ('Born_height', models.PositiveBigIntegerField()),
                ('Born_weight', models.PositiveBigIntegerField()),
                ('Method_Used_in_Birth', models.CharField(max_length=100)),
                ('Midwife_name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Medical Infos',
            },
        ),
        migrations.CreateModel(
            name='Vacinne_and_measure',
            fields=[
                ('VID', models.PositiveBigIntegerField(primary_key=True, serialize=False)),
                ('Vacinne_name', models.CharField(max_length=100)),
                ('Details', models.TextField()),
                ('Age_Limit', models.PositiveIntegerField()),
                ('Time_to_inject', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('HID', models.PositiveBigIntegerField(primary_key=True, serialize=False)),
                ('Names', models.CharField(max_length=100)),
                ('Hospitaltype', models.TextField()),
                ('LocationId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Hospital', to='ikibondoapp.location')),
            ],
        ),
        migrations.CreateModel(
            name='CHW',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('HID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chw_profile', to='ikibondoapp.hospital')),
                ('LocationId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chw_profile', to='ikibondoapp.location')),
            ],
        ),
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('NID', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('Age', models.PositiveIntegerField()),
                ('Phone', models.CharField(max_length=10)),
                ('Role', models.CharField(choices=[('Admin', 'Admin'), ('Parent', 'Parent'), ('CHW', 'CHW')], max_length=50)),
                ('Location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ikibondoapp.location')),
            ],
            options={
                'verbose_name_plural': 'Parents',
            },
        ),
        migrations.CreateModel(
            name='Baby',
            fields=[
                ('BID', models.PositiveBigIntegerField(primary_key=True, serialize=False)),
                ('Names', models.CharField(max_length=100)),
                ('Gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=30)),
                ('Age', models.PositiveIntegerField()),
                ('Photo', models.ImageField(blank=True, default='default.png', upload_to='')),
                ('PID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Baby', to='ikibondoapp.parent')),
            ],
            options={
                'verbose_name_plural': 'Babies',
            },
        ),
        migrations.CreateModel(
            name='VaccinatedBaby',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Doze', models.TextField()),
                ('Timetaken', models.TimeField(auto_now=True)),
                ('BID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Gives', to='ikibondoapp.baby')),
                ('HID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Gives', to='ikibondoapp.hospital')),
                ('VID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='VaccinatedBabies', to='ikibondoapp.vacinne_and_measure')),
            ],
            options={
                'verbose_name_plural': 'VaccinatedBabies',
            },
        ),
        migrations.CreateModel(
            name='Update',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('New_height', models.PositiveBigIntegerField()),
                ('New_weight', models.PositiveBigIntegerField()),
                ('Description', models.TextField()),
                ('Date', models.DateField(auto_now=True)),
                ('BID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Update', to='ikibondoapp.baby')),
                ('VID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Update', to='ikibondoapp.vacinne_and_measure')),
            ],
            options={
                'verbose_name_plural': 'Updates',
            },
        ),
    ]
