# Generated by Django 5.1.3 on 2024-12-02 05:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ikibondoapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='Province',
            new_name='Provence',
        ),
        migrations.RemoveField(
            model_name='chw',
            name='Phone',
        ),
        migrations.AddField(
            model_name='location',
            name='Streetcode',
            field=models.CharField(default=1234, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='parent',
            name='Location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ikibondoapp.location'),
        ),
    ]
