# Generated by Django 5.1.3 on 2024-12-02 09:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ikibondoapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Baby',
            fields=[
                ('BID', models.PositiveBigIntegerField(primary_key=True, serialize=False)),
                ('Names', models.CharField(max_length=100)),
                ('Gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=30)),
                ('Age', models.PositiveIntegerField()),
                ('Photo', models.ImageField(blank=True, default='default.png', upload_to='')),
                ('PID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Baby', to='ikibondoapp.parent')),
            ],
            options={
                'verbose_name_plural': 'Babies',
            },
        ),
    ]
