# Generated by Django 5.1.3 on 2024-12-14 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ikibondoapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Device',
        ),
    ]
