# Generated by Django 5.1.3 on 2024-12-13 07:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ikibondoapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='Age',
            field=models.PositiveIntegerField(null=True, validators=[django.core.validators.RegexValidator(code='invalid_age_value', message='age must be 2 digits long.', regex='^\\d{2}$')]),
        ),
    ]
