# Generated by Django 5.1.3 on 2024-12-14 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ikibondoapp', '0002_delete_device'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('UserGuide', models.TextField()),
                ('Description', models.CharField(max_length=100)),
                ('SerialNumber', models.PositiveBigIntegerField()),
                ('Img', models.ImageField(default='device.png', null=True, upload_to='')),
            ],
        ),
    ]
