# Generated by Django 5.1.3 on 2024-12-15 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ikibondoapp', '0002_baby_device_feedback_location_vacinne_and_measure_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='baby',
            name='PID',
        ),
    ]
