# Generated by Django 5.1.3 on 2024-12-13 09:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ikibondoapp', '0002_alter_myuser_age'),
    ]

    operations = [
        migrations.CreateModel(
            name='Approval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True, help_text='Approval comments', null=True)),
                ('time_created', models.DateTimeField(default=True, help_text='Time approval was created')),
                ('approvers', models.ManyToManyField(help_text='Users who approve', related_name='approval_approvers', to=settings.AUTH_USER_MODEL)),
                ('approves', models.ManyToManyField(help_text='Users being approved', related_name='approved_users', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Approval',
                'verbose_name_plural': 'Approvals',
                'ordering': ['-time_created'],
            },
        ),
    ]
