# Generated by Django 5.1.3 on 2024-12-02 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ikibondoapp', '0002_baby'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FUll_Name', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=254)),
                ('Subject', models.CharField(max_length=100)),
                ('Message', models.TextField()),
                ('CreatedDate', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Feedbacks',
            },
        ),
    ]
