# Generated by Django 5.1.3 on 2024-12-02 09:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ikibondoapp', '0003_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='Update',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('New_height', models.PositiveBigIntegerField()),
                ('New_weight', models.PositiveBigIntegerField()),
                ('Description', models.TextField()),
                ('Date', models.DateField(auto_now=True)),
                ('BID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Update', to='ikibondoapp.baby')),
                ('VID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Update', to='ikibondoapp.vacinne_and_measure')),
            ],
            options={
                'verbose_name_plural': 'Updates',
            },
        ),
    ]
