# Generated by Django 5.1.3 on 2024-12-15 22:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ikibondoapp', '0003_remove_baby_pid'),
    ]

    operations = [
        migrations.AddField(
            model_name='baby',
            name='PID',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Baby', to='ikibondoapp.parent'),
            preserve_default=False,
        ),
    ]
