# Generated by Django 5.1.3 on 2024-12-13 09:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ikibondoapp', '0003_approval'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approval',
            name='time_created',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Time approval was created'),
        ),
    ]
