# Generated by Django 5.1.3 on 2024-12-04 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ikibondoapp', '0003_parent_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CHW',
        ),
    ]
