# Generated by Django 5.1.3 on 2024-12-14 16:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ikibondoapp', '0003_device'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parent',
            name='Location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location', to='ikibondoapp.location'),
        ),
    ]
