# Generated by Django 5.1.3 on 2024-12-02 09:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ikibondoapp', '0004_update'),
    ]

    operations = [
        migrations.CreateModel(
            name='VaccinatedBaby',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Doze', models.TextField()),
                ('Timetaken', models.TimeField(auto_now=True)),
                ('BID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Gives', to='ikibondoapp.baby')),
                ('HID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Gives', to='ikibondoapp.hospital')),
                ('VID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='VaccinatedBabies', to='ikibondoapp.vacinne_and_measure')),
            ],
            options={
                'verbose_name_plural': 'VaccinatedBabies',
            },
        ),
    ]
