# Generated by Django 5.1.3 on 2024-12-04 20:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ikibondoapp', '0004_delete_chw'),
    ]

    operations = [
        migrations.CreateModel(
            name='CHW',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('HID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chw_profile', to='ikibondoapp.hospital')),
                ('LocationId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chw_profile', to='ikibondoapp.location')),
                ('User', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
