# Generated by Django 5.1.3 on 2024-12-14 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ikibondoapp', '0004_alter_parent_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='Description',
            field=models.TextField(),
        ),
    ]
