# Generated by Django 5.1.3 on 2024-12-05 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ikibondoapp', '0005_chw'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parent',
            name='Phone',
        ),
        migrations.RemoveField(
            model_name='parent',
            name='Role',
        ),
    ]
