# Generated by Django 5.1.3 on 2024-12-15 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ikibondoapp', '0005_alter_baby_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baby',
            name='BID',
            field=models.PositiveIntegerField(primary_key=True, serialize=False),
        ),
    ]
