# Generated by Django 5.1.3 on 2024-12-15 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ikibondoapp', '0005_alter_device_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='Img',
            field=models.ImageField(default='device.png', null=True, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='location',
            name='LocationId',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
