# Generated by Django 5.1.3 on 2024-12-15 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ikibondoapp', '0006_alter_device_img_alter_location_locationid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='baby',
            name='PID',
        ),
        migrations.AddField(
            model_name='baby',
            name='PID',
            field=models.ManyToManyField(related_name='Baby', to='ikibondoapp.parent'),
        ),
    ]
