# Generated by Django 5.1.3 on 2024-12-15 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ikibondoapp', '0008_remove_baby_age_remove_medical_info_dob_baby_dob_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medical_info',
            name='Age',
            field=models.PositiveIntegerField(help_text='age in mouths'),
        ),
    ]
