# Generated by Django 5.1.3 on 2024-12-15 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ikibondoapp', '0009_alter_medical_info_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='Recordeddate',
            field=models.IntegerField(default=2024),
            preserve_default=False,
        ),
    ]
