# Generated by Django 5.1.3 on 2024-12-05 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ikibondoapp', '0009_device_feedback_location_medical_info_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='baby',
            name='PID',
        ),
        migrations.RemoveField(
            model_name='vaccinatedbaby',
            name='BID',
        ),
        migrations.RemoveField(
            model_name='update',
            name='BID',
        ),
        migrations.RemoveField(
            model_name='chw',
            name='HID',
        ),
        migrations.RemoveField(
            model_name='chw',
            name='LocationId',
        ),
        migrations.RemoveField(
            model_name='chw',
            name='User',
        ),
        migrations.DeleteModel(
            name='Device',
        ),
        migrations.DeleteModel(
            name='Feedback',
        ),
        migrations.RemoveField(
            model_name='hospital',
            name='LocationId',
        ),
        migrations.RemoveField(
            model_name='vaccinatedbaby',
            name='HID',
        ),
        migrations.RemoveField(
            model_name='parent',
            name='Location',
        ),
        migrations.DeleteModel(
            name='Medical_info',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='user_permissions',
        ),
        migrations.RemoveField(
            model_name='parent',
            name='user',
        ),
        migrations.RemoveField(
            model_name='update',
            name='VID',
        ),
        migrations.RemoveField(
            model_name='vaccinatedbaby',
            name='VID',
        ),
        migrations.DeleteModel(
            name='Baby',
        ),
        migrations.DeleteModel(
            name='CHW',
        ),
        migrations.DeleteModel(
            name='Hospital',
        ),
        migrations.DeleteModel(
            name='Location',
        ),
        migrations.DeleteModel(
            name='Myuser',
        ),
        migrations.DeleteModel(
            name='Parent',
        ),
        migrations.DeleteModel(
            name='Update',
        ),
        migrations.DeleteModel(
            name='VaccinatedBaby',
        ),
        migrations.DeleteModel(
            name='Vacinne_and_measure',
        ),
    ]
